insert into motivo(id_motivo,desc_motivo) values (1,'Economicos');
insert into motivo(id_motivo,desc_motivo) values (2,'Salud');
insert into motivo(id_motivo,desc_motivo) values (3,'Laboral');
insert into motivo(id_motivo,desc_motivo) values (4,'Tramite');
insert into motivo(id_motivo,desc_motivo) values (5,'No entiendo la materia');
insert into motivo(id_motivo,desc_motivo) values (6,'No le entiendo al profesor');
insert into motivo(id_motivo,desc_motivo) values (7,'Me quede dormido');
insert into motivo(id_motivo,desc_motivo) values (8,'Problemas familiares varios');
insert into motivo(id_motivo,desc_motivo) values (9,'Problemas con el transporte');
insert into motivo(id_motivo,desc_motivo) values (10,'Actividad extra-programatica del instituto');
insert into motivo(id_motivo,desc_motivo) values (11,'Otros');